=== KasturiRanganR4/Web_Technology_lab_programs/5_program__xml/stud.dtd
<?xml version="1.0"?>
<!ELEMENT information (vtu+)>
<!ELEMENT usn (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT college (#PCDATA)>
<!ELEMENT branch (#PCDATA)>
<!ELEMENT yoj (#PCDATA)>
<!ELEMENT email (#PCDATA)>

=== KasturiRanganR4/Web_Technology_lab_programs/5_program__xml/studentinfo.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE student_information SYSTEM "stud.dtd">
<?xml-stylesheet type="text/css" href="stud.css"?>

<!-- Design an XML document to store information about a student in an engineering college affiliated to VTU. 
The information must include USN, Name, and Name of the College, Branch, Year of Joining, and email id. 
Make up sample data for 3 students. Create a CSS style sheet and use it to display the document.-->

<information>

<vtu>
<usn> 4VV18IS001 </usn>
<name> Ram </name>
<college> VVCE </college>
<branch> ISE </branch>
<yoj> 2018 </yoj>
<email> ram@gmail.com </email>
</vtu>

<vtu>
<usn> 4VV18IS002 </usn>
<name> Harsha </name>
<college> VVCE </college>
<branch> ISE </branch>
<yoj> 2018 </yoj>
<email> harsha@gmail.com </email>
</vtu>

<vtu>
<usn> 4VV18IS003 </usn>
<name> Siri </name>
<college> VVCE </college>
<branch> ISE </branch>
<yoj> 2018 </yoj>
<email> siri@gmail.com </email>
</vtu>

</information>
